name: storage_manager
description: Manages local storage.
version: 0.8.0
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  firebase_storage: ^11.0.3
  flutter:
    sdk: flutter
  flutter_download_manager:
    git: 
      url: https://github.com/simplecohesion/flutter_download_manager
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1

flutter:
